#define svayam auto
#define satat const
#define bamnu double
#define dashaansh float
#define purnaank int
#define tunko short
#define rachna struct
#define chihna_vagar_no unsigned
#define roki_do break
#define calu_rakho continue
#define nahi_to else
#define maate for
#define laambo long
#define chihna_valo signed
#define badalo switch
#define radBaatal void
#define maamlo case
#define mulbhut default
#define ganatri enum
#define jao_jya goto
#define patrak register
#define kad sizeof
#define olkho typedef
#define asthir volatile
#define prateek char
#define karo do
#define baahya extern
#define jo if
#define parat_karo return
#define sthir static
#define sangh union
#define jya_sudhi while
#define mukhya main
#define chhapo printf
#define tapaaso scanf

